## Bootstrap Samplingの例
ここでは以下の記事のコードを転載（一部追加あり）   
https://qiita.com/tjmnmn/items/3aed6fb85f75446f74ca

In [1]:
from sklearn.utils import resample
import numpy

In [2]:
# [0,1,2,...,9]と[10,11,12,...,19]の生成
data_x = [i for i in range(10)]
data_y = [i+10 for i in range(10)]


In [3]:
# K:再標本化の回数 SIZE:再標本化されたもののサンプルサイズ
K = 10
SIZE = len(data_x)

# bootstrap sampling
for i in range(K):
    # sklearnでもnumpyでもどちらでも大丈夫
    resampled_data_x = numpy.random.choice(data_x, size=SIZE)
    resampled_data_y = numpy.random.choice(data_y, size=SIZE)
    #resampled_data_x, resampled_data_y = resample(data_x,data_y, 
                                                   #n_samples = SIZE)
    print("------%d resample ------"% i)
    print(resampled_data_x)
    print(resampled_data_y)

------0 resample ------
[0 6 5 1 5 3 4 2 5 0]
[13 14 19 12 19 13 14 10 13 19]
------1 resample ------
[9 2 2 3 9 2 9 4 5 4]
[19 12 10 14 12 15 19 10 11 16]
------2 resample ------
[7 4 2 9 1 9 4 0 0 7]
[14 17 13 15 13 18 16 10 16 13]
------3 resample ------
[6 3 4 7 2 6 8 2 2 2]
[17 10 18 12 11 19 15 19 14 14]
------4 resample ------
[7 7 4 9 8 8 1 1 4 1]
[13 18 16 12 15 17 10 13 16 17]
------5 resample ------
[5 9 5 8 9 3 2 4 7 8]
[14 19 17 11 14 19 10 15 14 14]
------6 resample ------
[6 8 7 3 6 2 7 8 8 9]
[10 18 13 13 12 16 10 16 16 13]
------7 resample ------
[8 7 2 4 7 3 0 6 1 9]
[12 16 19 18 18 15 11 13 11 19]
------8 resample ------
[8 2 0 1 4 8 1 8 4 6]
[14 13 14 12 11 10 17 13 15 13]
------9 resample ------
[3 0 5 8 2 9 0 8 7 8]
[19 13 19 16 18 13 12 15 19 11]
